language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: QTDIR=/opt/qt54 PATH=$PATH:$QTDIR/bin
    - os: osx
      osx_image: xcode7.2

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt542-trusty
    packages:
    - qt54base

#env:
#  global:
#  - QTDIR=/opt/qt54 PATH=$PATH:$QTDIR/bin


script:
- mkdir build
- cd build
- cmake ..
- make
- xvfb-run ctest
