language: cpp

sudo: required

os:   linux
dist: wily

addons:
  apt:
#    sources:
#    - sourceline: ppa:beineri/opt-qt542-trusty
#    packages:
#    - qtbase5-dev

#env:
#  global:
#  - QTDIR=/opt/qt54 PATH=$PATH:$QTDIR/bin


compiler: 
- clang
- gcc

script:
- mkdir build
- cd build
- cmake ..
- make
- make test
