language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt542-trusty
    packages:
    - qt54base

env:
  global:
  - QTDIR=/opt/qt54 PATH=$PATH:$QTDIR/bin


script:
- mkdir build
- cd build
- cmake ..
- make
- xvfb-run ctest
