# adapted from travis-qt5-playground

sudo: required
dist: trusty
language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

env:
  - BUILD_TYPE=Debug
    BUILD_COVERAGE=TRUE
  - BUILD_TYPE=Release
    BUILD_COVERAGE=FALSE

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "clang++" ]; then export MKSPEC=linux-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" ]; then export MKSPEC=linux-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export MKSPEC=macx-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "g++" ]; then export MKSPEC=macx-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y update -qq && sudo apt-get -y install qt5-default; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH; fi

#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script:
    - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_COVERAGE=${BUILD_COVERAGE}
    - make
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then xvfb-run make test; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then make test; fi

after_success:
  - if [ $BUILD_COVERAGE ]; then rm -rf external; bash <(curl -s https://codecov.io/bash); fi
