language: cpp

sudo: required

os:   linux
dist: trusty

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt542-trusty
    packages:
    - qt54base

env:
  global:
  - QTDIR=/opt/qt54 PATH=$PATH:$QTDIR/bin


compiler: 
- clang
- gcc

script:
- mkdir build
- cd build
- cmake ..
- make
- make test
