
image: Visual Studio 2015

platform: x64

configuration:
  - Release 
  - Debug

environment:
  global:
    QTDIR: C:\Qt\5.7\msvc2015_64
    #PATH: C:\Qt\5.7\msvc2015_64;%PATH%
  matrix: 
    - BUILD_SYSTEM: "Visual Studio 14 2015 Win64"
      QTDIR: C:\Qt\5.7\msvc2015_64
    - BUILD_SYSTEM: "Visual Studio 14 2015"
      QTDIR: C:\Qt\5.7\msvc2015

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -G"%BUILD_SYSTEM%"

build_script:
  - cmake --build . --config ${configuration}

test_script:
- ctest
