
image: Visual Studio 2015

platform: x86

configuration: Release

environment:
  matrix: 
    - QTDIR: "C:\\Qt\\5.7\\msvc2015"
      PATH: "%PATH%;C:\\Qt\\5.7\\msvc2015\\bin"
      BUILD_SYSTEM: "Visual Studio 14 2015"
    - QTDIR: "C:\\Qt\\5.7\\msvc2015_64"
      PATH: "C:\\MinGW\\bin;C:\\Qt\\5.7\\mingw53_32\\bin;%PATH%"
      BUILD_SYSTEM: "MingGW Makefiles"
      C_COMPILER: clang
      CXX_COMPILER: clang++

before_build:
  - mkdir build
  - cd build
  - cmake -G"%BUILD_SYSTEM%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="%C_COMPILER%" -DCMAKE_CXX_COMPILER="%CXX_COMPILER%" ..

build_script:
  - cmake --build . --config Release

test_script:
  - ctest
