
image: Visual Studio 2015

platform: x64

configuration: Release

environment:
  matrix: 
    - QTDIR: "C:\\Qt\\5.7\\msvc2015_64"
      PATH: "%PATH%;C:\\Qt\\5.7;C:\\Qt\\5.7\\msvc2015_64\\bin"
      BUILD_SYSTEM: "Visual Studio 14 2015 Win64"
    - QTDIR: "C:\\Qt\\5.7\\msvc2015_64"
      PATH: "%PATH%;C:\\Qt\\5.7;C:\\Qt\\5.7\\msvc2015_64\\bin"
      BUILD_SYSTEM: "NMake"
      CMAKE_C_COMPILER: clang
      CMAKE_CXX_COMPILER: clang++

before_build:
  - mkdir build
  - cd build
  - cmake -G"%BUILD_SYSTEM%" -DCMAKE_BUILD_TYPE=Release ..

build_script:
  - cmake --build . --config Release

test_script:
  - ctest
