
image: Visual Studio 2015

platform: x64

configuration: Release

#install:
#  ############################################################################
#  # Install Ninja
#  ############################################################################
#  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
#  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
#  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
#  - set PATH=C:\projects\deps\ninja;%PATH%
#  - ninja --version

environment:
  matrix: 
    - QTDIR: "C:\\Qt\\5.7\\msvc2015_64"
      PATH: "%PATH%;C:\\Qt\\5.7\\msvc2015_64\\bin"
      BUILD_SYSTEM: "Visual Studio 14 2015 Win64"
      TOOLCHAIN: "v140"
    - QTDIR: "C:\\Qt\\5.7\\msvc2015_64"
      PATH: "C:\\Program Files\\LLVM\\bin;C:\\Qt\\5.7\\msvc2015_64\\bin;%PATH%"
      BUILD_SYSTEM: "Visual Studio 14 2015 Win64"
      TOOLCHAIN:  "LLVM-vs2014" 

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "%BUILD_SYSTEM%" -DCMAKE_BUILD_TYPE=Release -T%TOOLCHAIN%
  #- cmake -G"%BUILD_SYSTEM%" -T"%TOOLCHAIN%" -DCMAKE_BUILD_TYPE=Release ..

build_script:
  - cmake --build . --config Release

test_script:
  - ctest
