
image: Visual Studio 2015

platform: x64

configuration: Release

environment:
    QTDIR: "C:\\Qt\\5.7\\msvc2015_64"
    PATH: "%PATH%;C:\\Qt\\5.7;C:\\Qt\\5.7\\msvc2015_64\\bin"

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..

build_script:
  - cmake --build . --config Release

test_script:
  - ctest
