if(CMAKE_VERSION VERSION_LESS "3.1")
  message("Warning: cmake version less than 3.1")
  if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    # using regular Clang or AppleClang
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
  endif()
  if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
  endif()
else()
  message("cmake version at least 3.1; setting CMAKE_CXX_VERSION = 11")
  set(CMAKE_CXX_STANDARD 11)
endif()
